initial commit
blckbrd-dev/lightning-rager pull request #1
Opened 2017-04-18 16:36 UTC by rastko1996

Although many things are already done, this is initial commit to the repo.

2017-04-18 17:08 UTC, gavrilovmiroslav requested changes
So many C things, so little C++. :) 🥇

2017-04-18 17:08 UTC, gavrilovmiroslav commented on include/cell.h
> +#ifndef CELL_H_
`#pragma once` is always preferred to guards in C++

2017-04-18 17:08 UTC, gavrilovmiroslav commented on include/cell.h
> +	mutable Uint16 x, y;
No reason to use mutable like this, especially for something as simple as this.

2017-04-18 17:08 UTC, gavrilovmiroslav commented on include/cell.h
> +	inline void set_x(const Uint16) const;
Setters? This is a POD (Plain Old Data), make data public and don't overthink it.

2017-04-18 17:08 UTC, gavrilovmiroslav commented on include/cell.h
> +	inline void set_x(const Uint16) const;
Also, const Uint16 everywhere, even though you're changing the values. *slow clap*

2017-04-18 17:08 UTC, gavrilovmiroslav commented on include/color.h
> +	mutable int m_color;
Same comments as in `Cell`, don't do this like this. Make it a struct, add members, be done.

2017-04-18 17:08 UTC, gavrilovmiroslav commented on include/screen.h
> +	Uint32* m_buffer;
All of these could be wrapped in `std::unique_ptr` for safety. This will raise bugs if you mishandle pointers.

2017-04-18 17:08 UTC, gavrilovmiroslav commented on include/vmonitor.h
> +#ifndef VMONITOR_H_
Replace guards with `#pragma once`

2017-04-18 17:08 UTC, gavrilovmiroslav commented on include/vmonitor.h
> +	mutable Uint32** matrix;
Should have used `eigen`

2017-04-18 17:08 UTC, gavrilovmiroslav commented on include/vmonitor.h
> +	void set_matrix(Uint32**) const;
Too much pointer-passing for clear, pragmatic C++.

2017-04-18 17:08 UTC, gavrilovmiroslav commented on src/misc/cell.cpp
> +
All of these are now not needed because you have header-only structs.

2017-04-18 17:08 UTC, gavrilovmiroslav commented on src/misc/color.cpp
> +
All of these are now not needed because you have header-only structs.

2017-04-18 17:08 UTC, gavrilovmiroslav commented on src/screen/screen.cpp
> +#define delete(x) { delete x; x = NULL; }
Don't OVERRIDE `delete`, call it different, like `del`.

2017-04-18 17:08 UTC, gavrilovmiroslav commented on src/screen/screen.cpp
> +		m_texture = SDL_CreateTexture(m_renderer,
You're using `m_renderer` without being sure it's actually allocated at this point. `STD_CreateRenderer` could fail?

2017-04-18 17:08 UTC, gavrilovmiroslav commented on src/screen/screen.cpp
> +			m_buffer[i] = 0x00FF00FF;
Mother of all pointer fluff-balls.

2017-04-20 11:54 UTC, rastko1996 commented on include/screen.h
> +	Uint32* m_buffer;
If I do this, then I do not have to take care of deleting these, since smart pointer does that automatically?

2017-04-20 14:54 UTC, gavrilovmiroslav approved these changes

2017-04-20 14:55 UTC, merged